### ISSUE TITLE
Add Privacy Manifest

### ISSUE THREAD

**Issue by chrs1885** [CheekyGhost-Labs/SyntaxSparrow#27]
Hi there,

We recently became aware that, according to the new Apple privacy regulations, third-party SDKs will also be required to provide a [Privacy Manifest ](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) to ensure compliance with privacy policies in the future.

Do you have any plans to deliver a Privacy Manifest with the library?

**Comment by mobrien-ghost** [comment]
Hi, 

Yes absolutely. Fortunately I should have time this weekend to get it added in (I will need to do the same for some other libraries too). First glance looks like it will be simple, however, I want to look into the required reason API section to ensure I don't need to declare anything source-file related for swift-syntax (timestamps or file attributes and the like). Will post back once it's sorted 👍

**Comment by mobrien-ghost** [comment]
Update: Finally heard back from Apple (though given Christmas time, wait was understandable 😅). Should be able to sort this out tonight and verify for a PR.

**Comment by mobrien-ghost** [comment]
Created the PR, have also validated it will show up in the privacy report of consuming applications/projects etc. If interested, I updated a forum post with the response I got from apple + validation (as the Apple docs were not explicitly clear for standard Swift packages). **[Forum Post Here](https://developer.apple.com/forums/thread/742527?answerId=775992022#775992022)**
