### ISSUE TITLE
Apple to Swiftlang Organization

### ISSUE THREAD

**Issue by manuelkunzdmde** [CheekyGhost-Labs/SyntaxSparrow#50]
<img width="737" alt="Screenshot 2024-07-29 at 16 09 11" src="https://github.com/user-attachments/assets/0c9c8689-a84c-4be5-90f8-a5552e7ef4ae">

Currently getting this warning in package resolution in my project.
This seems to be no problem yet but will be in the future.
Problem seems to be that the swift-syntax repo is used from two different orgs.
In my understanding Apple wants us to use the package from the swiftlang org.
Could you provide a fix for this in your Package.swift?

Thanks in advance :)

**Comment by mobrien-ghost** [comment]
PR Here: https://github.com/CheekyGhost-Labs/SyntaxSparrow/pull/51

**Comment by mobrien-ghost** [comment]
Latest patch release (4.2.1) should resolve. Please lemme know when you get a chance to confirm and will close the issue.
